# Generated by Django 2.1.7 on 2020-02-15 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedrooms',
            new_name='Quantity',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.AddField(
            model_name='listing',
            name='ReadyBy',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
